feat:
  - head-branch: ['^feat/']
  - title: '^feat:.*'

fix:
  - head-branch: ['^fix/']
  - title: '^fix:.*'

docs:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '*.md']
  - title: '^docs:.*'

refactor:
  - title: '^refactor:.*'

style:
  - title: '^style:.*'

test:
  - changed-files:
      - any-glob-to-any-file: ['**/*.test.js', '**/*.spec.ts']
  - title: '^test:.*'

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
  - title: '^ci:.*'

chore:
  - title: '^chore:.*'
